Implement Dynamic Search Functionality for Search Bar
dohinaf/basic-icecream-website pull request #253
Opened 2024-10-06 14:51 UTC by Akshita246

I implement a dynamic search functionality for the menu items of the website. This feature allows users to easily search and filter ice cream flavors by typing in the search bar. As they type, the page automatically updates to show only the matching items, improving user experience and making it more convenient for customers to find their desired flavors.
Changes Made:
Implemented JavaScript functionality to update the displayed menu items based on the search input in real-time.
Improved the user interface to provide a more seamless and intuitive search experience.
Related Issues:
Closes #247 .
Before:
![ArcticDelights - Google Chrome 06-10-2024 20_16_34](https://github.com/user-attachments/assets/778213ba-a135-4e4b-9cb5-4d1fe20b6bdf)
After:
![ArcticDelights - Google Chrome 06-10-2024 20_04_34](https://github.com/user-attachments/assets/ff42009a-4fc0-4bba-a363-9541dfd303a5)

2024-10-07 13:32 UTC, Akshita246 commented
Hi @dohinafs ,

I hope you're doing well! I have submitted this PR as part of Hacktoberfest and GSSOC, and if you find it helpful, could you please add the `hacktoberfest-accepted` label?

Thank you for your time and consideration!

2024-10-09 04:37 UTC, Altair-05 commented
<img width="917" alt="image" src="https://github.com/user-attachments/assets/c0220bda-dfc6-4a4f-b05f-277188956f9d">
@Akshita246, the changes you made are not appearing here.  please check and update accordingly?

2024-10-09 04:37 UTC, Altair-05 commented
@Akshita246  Also can you tell me  issue number of this pr?

2024-10-09 04:42 UTC, Akshita246 commented
its #247

On Wed, Oct 9, 2024 at 10:08 AM Altair ***@***.***> wrote:

> @Akshita246 <https://github.com/Akshita246> Also can you tell me issue
> number of this pr?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dohinaf/basic-icecream-website/pull/253#issuecomment-2401298390>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBW6TDHUFUSX43PHII2MLA3Z2SXLZAVCNFSM6AAAAABPOMR72SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBRGI4TQMZZGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-09 05:03 UTC, Akshita246 commented
Hello i just checked and found out that the filter part of the code is not
responsive though it is not working. As my pull request #247 was for the
search bar which is present in the nav bar , I am going to raise another
issue for the filter part  so please assign me that under gssoc and
hacktoberfest

On Wed, Oct 9, 2024 at 10:07 AM Altair ***@***.***> wrote:

> image.png (view on web)
> <https://github.com/user-attachments/assets/c0220bda-dfc6-4a4f-b05f-277188956f9d>
> @Akshita246 <https://github.com/Akshita246>, the changes you made are not
> appearing here. please check and update accordingly?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dohinaf/basic-icecream-website/pull/253#issuecomment-2401297341>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBW6TDAKSUR6UWCT56UWBRLZ2SXILAVCNFSM6AAAAABPOMR72SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBRGI4TOMZUGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-09 12:02 UTC, Akshita246 commented
Hi this is to inform you that someone changed the some of the template and
cursor setting due to which the wishlist , cart and the search bar and
filter functionality which I have changed is not working please make sure
that if someone is changing anything it should not affect the existing
functionality of other

On Wed, 9 Oct 2024, 10:08 am Altair, ***@***.***> wrote:

> @Akshita246 <https://github.com/Akshita246> Also can you tell me issue
> number of this pr?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dohinaf/basic-icecream-website/pull/253#issuecomment-2401298390>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBW6TDHUFUSX43PHII2MLA3Z2SXLZAVCNFSM6AAAAABPOMR72SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBRGI4TQMZZGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-09 13:27 UTC, Altair-05 commented on index.html
> +=======
why u used script tags without any use?

2024-10-09 13:31 UTC, Altair-05 requested changes

2024-10-09 13:31 UTC, Altair-05 commented on script.js
> +            item.style.display = '';  // Show the item if it matches
Items are not displayed after clicking the search button. Please review this function

2024-10-09 13:31 UTC, Altair-05 commented on index.html
> +      </script>
Why did you use script tags without any functionality?

2024-10-09 13:36 UTC, Akshita246 commented on script.js
> +            item.style.display = '';  // Show the item if it matches
Ok Let me be very clear the person who change the syling of the site disabled the functionalities of even the wishlist, add to cart and the search bar  and even the button of add to cart is not working so now i have to review all the code again give me some time

2024-10-09 14:02 UTC, Akshita246 commented on index.html
> +      </script>
![index html - basic-icecream-website - Visual Studio Code 09-10-2024 19_31_04](https://github.com/user-attachments/assets/20c7a969-be7e-4066-9408-3508995a6e03)
but there is no such code

2024-10-09 14:52 UTC, Altair-05 commented on script.js
> +            item.style.display = '';  // Show the item if it matches
sure

2024-10-11 04:26 UTC, Akshita246 commented on script.js
> +            item.style.display = '';  // Show the item if it matches
I have updated the code you can now check the search icon and the filter functionalities .
![Uploading ArcticDelights - Google Chrome 11-10-2024 09_56_46.png…]()
![Uploading ArcticDelights - Google Chrome 11-10-2024 09_56_20.png…]()

2024-10-11 04:30 UTC, Akshita246 commented
I have resolved the issue of  the code of the filter and the search icon functionalities you can check and if there is no more problem please let me know so that i can close the pull request.
![Uploading ArcticDelights - Google Chrome 11-10-2024 09_56_20.png…]()
![Uploading ArcticDelights - Google Chrome 11-10-2024 09_56_46.png…]()

2024-10-14 17:25 UTC, dohinafs commented
Kindly resolve the conflicts

2024-10-15 05:49 UTC, closed without merging

2024-10-15 05:57 UTC, Akshita246 commented
> Kindly resolve the conflicts

which???