Login Page is updated Successfully
dohinaf/basic-icecream-website pull request #382
Opened 2024-10-09 13:09 UTC by HeartTick

#257 @dohinafs Login page has been updated successfully.
![image](https://github.com/user-attachments/assets/7c6c4bd2-7f84-4955-be8e-1d22903d3d6a)

2024-10-09 15:00 UTC, Altair-05 approved these changes

2024-10-10 08:09 UTC, HeartTick commented
Hello @Altair-05 can you please go through the code and merge the code so that i can work on further Issues in this webpage .

2024-10-10 08:16 UTC, Altair-05 requested changes
@HeartTick 
<img width="361" alt="image" src="https://github.com/user-attachments/assets/ac3151eb-6412-4686-847d-9af8ab95e245">

2024-10-10 08:16 UTC, Altair-05 commented on index.html
> +            <input type="password" class="pass-btn" placeholder="Password" required>
why the password placeholder is displayed again in this section?

2024-10-10 08:42 UTC, HeartTick commented
Can you check once again . because i can't see that line in my code editor.

2024-10-10 08:52 UTC, HeartTick commented
![image](https://github.com/user-attachments/assets/65d77b55-3118-49d9-ba62-c4a3c6452f78)
This is the ouput i am getting when i am running the code and i checked the code as well there is no sush line exist at that position.

2024-10-10 09:01 UTC, Altair-05 commented
@HeartTick, please check the deploy preview. You’ll see the issue there

2024-10-10 09:15 UTC, HeartTick commented
Ss I can see the error in preview but I can able to see the error in my local machine.
Can u guide me to resolve this issue.

2024-10-10 09:16 UTC, dohinafs reviewed
This is how it is appearing in the deployment preview:
![image](https://github.com/user-attachments/assets/5ec1ebe6-f633-4b38-972a-f0a3f08432dd)
Make necessary changes to fix above and if possible add more padding below the cone.

2024-10-10 09:18 UTC, HeartTick commented
Can I close this pull request and make a new one . Is that ok for you

2024-10-10 09:22 UTC, dohinafs commented
Yes you can

2024-10-10 10:24 UTC, closed without merging