Added Faq's section in the footer of the website
dohinaf/basic-icecream-website pull request #406
Opened 2024-10-10 10:01 UTC by BVPKARTHIKEYA

Added Faq's in the website
![image](https://github.com/user-attachments/assets/bf78bc7b-9558-41f1-8c36-500287ca2fef)
Hope you like it!! issue#351

2024-10-10 10:11 UTC, dohinafs requested changes
There are some issues:
1. There is space between different sections which doesn't look good:
![image](https://github.com/user-attachments/assets/092aa306-9995-4d6d-a755-8d53dbbbefca)
2. Add some more padding below and to the left and right of the faq section to make it look better. 
![image](https://github.com/user-attachments/assets/a8d2ce4c-a364-4de6-b6a7-680ae62defe4)

2024-10-10 10:43 UTC, BVPKARTHIKEYA commented
ok i will do the changes!!
thanks for your feedback!!

2024-10-10 10:58 UTC, BVPKARTHIKEYA commented
![image](https://github.com/user-attachments/assets/e33ee02e-76a4-4abd-a6e0-a6e4fc31b8b3)
Now it's looking more better!!
hope you like it 
please assign the required labels!! and close my issue if it's resolved

2024-10-10 11:10 UTC, dohinafs requested changes
There is some issue in the background and sections. This issue is only appearing in your PR, kindly resolve it. 
This is how the deployed preview looks like:
![image](https://github.com/user-attachments/assets/59b595fe-cf6a-44b3-a7ec-76554d78bef5)
![image](https://github.com/user-attachments/assets/7afb86ee-6d6b-4244-9657-c4c5da698eb5)
This is how it was before:
![image](https://github.com/user-attachments/assets/c51ec27c-63c2-4a70-af6d-778c4cd42bec)

2024-10-10 11:34 UTC, BVPKARTHIKEYA commented
ok i will do the changes!!
thanks for your feedback

2024-10-10 12:00 UTC, BVPKARTHIKEYA commented
changes are made wrt dark mode!!
Hope you like it!!

2024-10-10 12:25 UTC, BVPKARTHIKEYA commented
Now it's completely done!!
Kindly check out!!

2024-10-14 17:10 UTC, BVPKARTHIKEYA commented
your changes are made @dohinafs

2024-10-15 15:16 UTC, dohinafs requested changes
There is some issue in your implementation:
1.  This is how the header looks like:
![image](https://github.com/user-attachments/assets/1caed2f4-169c-4928-89fc-d88f9197b8e9)

2.This is how the rest of the section looks like:
In your preview:
![image](https://github.com/user-attachments/assets/c4c03f4d-7928-49a9-aab0-34cffc2b524a)
![image](https://github.com/user-attachments/assets/a89da660-0beb-4ed9-b190-c3ef019f9272)
Before:
![image](https://github.com/user-attachments/assets/2f1c0b19-08ba-4cb7-b922-637fc501c141)
![image](https://github.com/user-attachments/assets/5a96f5c9-6497-48b6-a216-fe24355a782c)
Kindly make the necessary fixes within two days.

2024-10-28 13:06 UTC, BVPKARTHIKEYA commented
it's done please approve my pr as we are approaching the deadline

2025-10-14 12:34 UTC, closed without merging