footer social icon and customer button hover text visible
dohinaf/basic-icecream-website pull request #542
Opened 2024-10-14 11:55 UTC by saumyayadav25

#### Issue #519 : Solved Customer button and footer social icons 

Issues can be seen in #519 .

After changes:

#### Customer button on hover

<img width="663" alt="Screenshot 2024-10-14 at 5 22 46 PM" src="https://github.com/user-attachments/assets/8259aff4-5482-4e90-a667-94d180190794">

#### Footer section social icons now visible
(also added a background color to footer to distinct it from the main content)
<img width="1303" alt="Screenshot 2024-10-14 at 5 22 38 PM" src="https://github.com/user-attachments/assets/b4449a5e-09aa-445f-a3c0-6e28bb2b1737">

2024-10-14 11:59 UTC, saumyayadav25 commented
@dohinafs kindly review this PR.

2024-10-15 03:31 UTC, saumyayadav25 commented
@dohinafs kindly review this PR.

2024-10-16 09:41 UTC, dohinafs requested changes
The text is not visible in dark mode. Kindly keep the footer black as it was in dark mode with the changes you've implemented occurring only in light mode. 
![image](https://github.com/user-attachments/assets/1ad71abc-2922-45e3-8195-e0e6fd028290)

2024-10-16 10:35 UTC, saumyayadav25 commented
@dohinafs requested changes are done. you can check them and do let me know if any other changes are required.

2024-10-17 15:40 UTC, dohinafs approved these changes

2024-10-17 15:40 UTC, merged